### PR TITLE
Feature activate share closes #175

### LINKED ISSUE #175: Include the carrot share feature
include the carrot share feature previously included in the 0.2 release

### PR DESCRIPTION
**Pull request by leosa83**
Share button actiavated

### CODE REVIEW

**Comment by leosa83** [comment]
@Davito163 @miladf Waiting for you feedback before merging this button (an mvp version):
http://projecthub-share.meteor.com
Dont get distracted by everything else; the above link is only for showing the share feature.

**Comment by miladf** [comment]
@leosa83 site is down bro. cannot see.

**Comment by leosa83** [comment]
@miladf It takes a couple of seconds for the instance to start up after having been inactive. Its up n running now.

**Comment by leosa83** [comment]
Will merge and hope for your approval.

**Pull request merged**
