### PR TITLE
Feature/issue68 projectpage filters. closes #68

### LINKED ISSUE #68: Create Projects collection filtering functions
#### User Story

As a user i want to filter the projects shown according to two arguments:
- Location
- Challenge category
#### Definition of done
- [x] Two dropdowns appear on project page
- [x] Dropdowns are automatically populated with values from Projects collection.
- [x] When default values are selected, all projects from Projects collection are shown on page.
- [x] When value in dropdown is selected, projects that match filter are shown on page.

### PR DESCRIPTION
**Pull request by 2ECC71**
This PR adds filtering functionality to allprojects page, /projects.

Filters for problemCategory and location is implemented.

We should probably add a reactive update of location dropdown based on value in problemCategory dropdown.

### CODE REVIEW

**Comment by 2ECC71** [comment]
aha, to far behind develop, will pull and implement with current develop instead.
Edit: aha again, turns out the viewProjects.html has changed to much, please advice @brylie

**Comment by brylie** [comment]
The code looks pretty good. I can help merge conflicts today. Will you be on Slack @loxtank?

**Comment by loxtank** [comment]
Super. I'll try in an hour.

**Comment by leosa83** [comment]
The conflicts and bugs have been resolved by the feature-projectsFilter branch, am i correct? @loxtank

**Comment by 2ECC71** [comment]
@leosa83 yes, if @brylie is ok with the changes.

**Comment by leosa83** [comment]
I will close this PR in any case since this branch is dead. Open it again if im wrong.

**Pull request closed without merging**
