### PR TITLE
Feature #77 search filter

### LINKED ISSUE #77: Add search feature for Projects collection
Create a basic search feature for the Projects collection.
# Definition of done
- [x] Search fields are chosen from projects collection
- [x] Search index is added to project (so that other fields, possibly from other collections, may be added to index)
- [ ] `ensureIndex` has been added to desired fields in Projects collection
- [x] The team is aware of the options for creating a search index spanning multiple collections
# Potential packages
- Meteor [Easy Search](http://matteodem.github.io/meteor-easy-search/getting-started/)
# Reference

The following articles may help when researching this feature:
- Meteor Capture: [Simple search pattern](http://meteorcapture.com/simple-search-pattern/)
- MeteorHacks: [Implementing an Instant Search Solution with Meteor](https://meteorhacks.com/implementing-an-instant-search-solution-with-meteor.html)
- MongoDB docs [db.collection.ensureIndex()](https://docs.mongodb.org/v3.0/reference/method/db.collection.ensureIndex/)

### LINKED ISSUE #78: Add search feature to front page
Based on issue #77, we will add a search button/user interface to the front page.
- [x] show searchResults and allProjects template dynamically based on if currently searching

### PR DESCRIPTION
**Pull request by leosa83**
Backend functionality added to the searchbar
Closes #77 (ensureIndex is left)
Close #78

### CODE REVIEW

**Comment by leosa83** [comment]
please review @mark-mcevoy @modsmoss

**Comment by modsmoss** [comment]
Great job!

**Comment by modsmoss** [comment]
There seems to be an old version of **navbar.html** in **main/client**. I think this came from the same merge that removed the logo. The up-to-date version is in main/client/header. @leosa83

**Comment by leosa83** [comment]
Ok thanks, will check it out @modsmoss ! Please keep your eyes open for any other mistakes.

**Pull request merged**
