### PR TITLE
Feature whatwedo page closes #151

### LINKED ISSUE #151: style What we do page according to mockup
# Definition of Done
- [x] Style according to mockup
  https://projects.invisionapp.com/share/HQ540EQ2S#/screens/118594701
- [ ] Develop content @Shahin89 
- [x] Create sectionWhatWeDo.html/css and style according to mockup
- [x] Create sectionHowItWorks.html/css and style according to mockup
  - [x] re-use some of the html from the jekyll site
  - [x] re-use some of the CSS from the jekyll site
- [x] Create sectionChildrenPics.html/css and style according to mockup
# Development

Is being developed in the branch in this PR #173

### PR DESCRIPTION
**Pull request by leosa83**
sectionHowItWorks template:
Styling needed

sectionChildrePics:
waiting for @Angamanga PR to merge and then reuse that code for this section.

### CODE REVIEW

**Comment by leosa83** [comment]
@virre Can you please help with the styling?

**Comment by leosa83** [comment]
@Angamanga I assigned you to this, i hope its OK. Otherwise just unassign.

**Comment by Angamanga** [comment]
Its ok!

**Comment by leosa83** [comment]
Jag ville uppatera develop med vad som fanns i branchen, därför stängdes denna PR. Du kan fortsätta på branchen och sedan skapa en ny PR. @Angamanga

**Pull request merged**
