### PR TITLE
Closes issue #124

### PR DESCRIPTION
**Pull request by Angamanga**
Please review, hardcoded link on landing page, 2 places.

### CODE REVIEW

**Comment by leosa83** [comment]
Sorry the issue explained it wrong:
The link you should have used for those buttons was; https://refugee1.typeform.com/to/dNCHCf
Where you should have hardcoded the link for this issue was in: beAPart.html

**Comment by Angamanga** [comment]
Which one is beAPart.html?

**Comment by leosa83** [comment]
projects/client/view/projectProfile

**Comment by Angamanga** [comment]
Ok, please have a look now :+1:

**Comment by leosa83** [comment]
Thanks! :)

**Pull request merged**
