### PR TITLE
From Ningjing about the knowledge hub page

### PR DESCRIPTION
**Pull request by adelablue**
Hi leo, I added the knowledge hub (don't know if the page belongs to this section). I don't have photoshop installed, so can't get all the pictures. I placed some placeholder in it.

### CODE REVIEW

**Comment by leosa83** [comment]
Thank you @adelablue :smile: 

Nice work :+1:

**Comment by adelablue** [comment]
Thanks! :D

On Fri, May 27, 2016 at 3:20 PM, leosa83 notifications@github.com wrote:

> Thank you @adelablue https://github.com/adelablue 😄
> 
> Nice work 👍
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/refugeetech/platform/pull/198#issuecomment-222144208,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABb89w9W7jIMejcOTTal_j0m-Yz1LmOtks5qFu-KgaJpZM4In_fU
> .

## 

Ningjing Chen
Pippi Långstrumps gatan 40
16870 Bromma

Email: adelablue@gmail.com
Tel: +46(0)735792117

**Comment by leosa83** [comment]
This section really belongs to the project hub, probably as the template "projects/view/singleProject/singleProjectDetailed" (to replace the current one). 

When you click on "what is a coordination challenge" you would conceptually be routed to the knowledge hub.

**Comment by leosa83** [comment]
If you are able to make that adjustment (including populating the template with data where applicable) i would be supergrateful and be ready to merge this pullrequest. Thanks!

**Comment by leosa83** [comment]
Dont worry about it @adelablue , im on it :)

**Pull request merged**
