### PR TITLE
Feature/issue178 Closes #178

### LINKED ISSUE #178: cleanup: remove boiler plate code and deactivate unused routes
All navbar buttons that are not used should be commented out
All routes not used should be commented out

### PR DESCRIPTION
**Pull request by Angamanga**
@leosa83 Please check if I understood this right...

### CODE REVIEW

**Comment by leosa83** [comment]
Did you remove all routes aswell not used?

**Comment by leosa83** [comment]
Otherwise it was ok, some things we are implementing in other issues and will deal with them then.

**Comment by leosa83** [comment]
with routes i mean flowrouter deifnitons

**Comment by Angamanga** [comment]
Ok, I'll sort the flow router definitions out too, but it will have to wait until tomorrow or sunday...

**Comment by Angamanga** [comment]
Routes out-commented :)

**Comment by leosa83** [comment]
Thank you Anna :)

**Pull request merged**
