### PR TITLE
Revert to same code as version 94eea89

### PR DESCRIPTION
**Pull request by brylie**

### CODE REVIEW

**Comment by leosa83** [comment]
I pushed the patch directly to develop, should i revert? https://github.com/refugeetech/platform/commit/d6014d246666adfc263dda8f7ad69c3ecc6ee57e

**Comment by brylie** [comment]
It is up to you.

**Comment by brylie** [comment]
My apologies for reverting the landing page templates.

**Comment by leosa83** [comment]
No worries :)

**Pull request closed without merging**
