### PR TITLE
Feature/project tags selectize. Closes #104

### LINKED ISSUE #95: Add the Tags collection to the project
# Parent issue
#86

### LINKED ISSUE #104: Add selectize.js widget to Project Tags field
The project tags field will contain an array of tag IDs. In order to help users select tags while allowing tag ID to be stored, we can add a select widget. For this task, Selectize.js may be sufficient.
# Definition of done
- [x] Schema, publication, subscription, etc have been created for Tags feature
- [x] Project tags field suggests tags as user types
- [x] Tags are stored in Tags collection
- [x] Project `tags` field contains array of selected tags
- [x] When user inputs new tag in `tags` select widget, the tag is created in the Tags collection
- [x] When new tag is created via Selectize widget, the tag appears in the tags list
# Reference

There is a [StackOverflow post](http://stackoverflow.com/questions/24366365/creating-an-item-if-not-already-exists-in-selectize-js-select-box-and-ajax-updat) describing how to add new tags in a Selectize.js callback.

Selectize.js documentation [describes `create` usage in the Options section](https://github.com/selectize/selectize.js/blob/master/docs/usage.md#options).

### PR DESCRIPTION
**Pull request by brylie**
Allow users to select from existing tags or add new tags to Tags collection, when adding new Projects
Closes #95

### CODE REVIEW

**Comment by brylie** [comment]
**Work in progress** Please do not merge this branch until "needs work" tag is removed.

**Comment by Angamanga** [comment]
Have tried lots of different things so far but not solved it yet. I think I am on it though so not giving up yet.

**Comment by Angamanga** [comment]
@brylie Please check my solution. I separated the creation of a new tag in the ui and the adding of the tag to the Tags-collection by using onItemAdd for the Tags.insert and now it is working.

**Comment by leosa83** [comment]
Wow great job @Angamanga !

**Comment by brylie** [comment]
@refugeetech/develop please review

**Comment by brylie** [comment]
@Angamanga what are your thoughts after reviewing the current code? Should we merge?

**Comment by leosa83** [comment]
Looks good to me.

**Comment by brylie** [comment]
OK, thanks for the review! :smiley:

**Pull request merged**
