### PR TITLE
feature/project-profile. Closes #81

### LINKED ISSUE #81: Implement MVP Project Profile feature
# Description

In order for users to view details about a given project, we need to plan/design a Project profile feature. 
## MVP

The MVP feature will have the following capabilities:
- Project title
- Project description
- Project 'metadata'
  - Launch date (year format)
  - Category
  - Location (City)
  - Target platform
  - Social media links
  - Website link
## MVP Enhancements

Subsequent iterations of the Project Profile feature will have the following capabilities:
- [x] Project photos (based on Project Media feature #83)
- [ ] Share link (based on Share Project feature #84)
- [x] Progress bar (based on Project Progress feature #85)
# Definition of done
## Design
- [x] Wireframe exists for Project view
  - [ ] Wireframe is monochrome (optionally one additional color to emphasize annotations)
  - [ ] Wireframe is annotated with each sub-component
  - [ ]  Wireframe indicates which sub-components are part of MVP
- [ ] Static mock-up exists showing only Project profile design (e.g. no extra page elements such as footers, page sections from different features, etc)
## Code structure
- [x] Folder/file structure exists for project feature
  - [x] folder/file structure follows a Meteor package based architecture
## Route #89
- [x] Route exists for viewing individual project
- [x] Route takes a `projectID` argument
- [x] Route renders `singleProject` template (component)
## Publication #89
- [x] `singleProject` publication exists
- [x] `singleProject` publication takes `projectId` argument
- [x] `singleProject` publication returns a database cursor
  - [x] database cursor receives project ID in `find()` method: `Projects.find(projectId)`
## Project profile component #89
- [x] `projectProfile` template exists
  - [x] `projectProfile` template gets Project ID from route in `onCreated` lifecycle callback
  - [x] `projectProfile` template subscribes to `singleProject` publication
    - [x] `projectId` is passed in to `singleProject` subscription

_Note:_ For the time being, the `projectProfile` component can also render all project data.
- [x] `projectProfile` renders all MVP fields
### Page header  #89
- [x] Project name is rendered as page header
  - [x] Project name markup contains Bootstrap `page-header` class (or equivalent)
### Project details  #89

The following fields render in a project details page element.
- [x] Launch date (year format)
- [x] Category
- [x] Location (City)
- [x] Target platform
- [x] Social media links
- [x] Website link
## HTML/CSS
- [x] UI Components are styled using Bootstrap semantics
  - [ ] Bootstrap classes are extended where needed, by inheritance
- [x] UI Components match color/design of styleguide
# Parent issue
#80
# Child issues
#89
# Design

rt_hub_wf_009_1_articlepage_v4_dt

### PR DESCRIPTION
**Pull request by leosa83**
Closes #81

### CODE REVIEW

**Comment by leosa83** [comment]
review please @brylie @mark-mcevoy

**Comment by brylie** [comment]
I can help with review here. 

Please add "Closes # ..." to the PR title in the future. This enables some advanced linking between PRs and issues on Github and Waffle.io.

**Comment by brylie** [comment]
We do not need to move the singleProject folder to a subfolder of allProjects. It can be used in multiple contexts, so it is OK to leave where it was.

**Comment by brylie** [comment]
I think we should label this PR as 'work-in-progress' with the WIP label, assign it as related to _implement the project profile_ issue, and continue developing the feature. There are a few reasons for this:
- we may not use all of the files here
- some of the file and folder names can be shortened/simplified, as they are implied by parent folders
- this PR does not implement any functionality

**Comment by leosa83** [comment]
The simple solution now is to delete this branch and use gitflow on develop and all related issues.

**Comment by leosa83** [comment]
Will close PR and delete branch

**Pull request closed without merging**
